[package]
authors = ["Stefan Kewatt <stefan.kewatt@gmail.com>"]
name = "code_page"
version = "0.1.0"
edition = "2021"

license-file = "LICENSE"
description = ""

[lib]
crate-type = ["rlib"]

[dependencies]
